package ui

import (
	"fmt"

	"github.com/charmbracelet/lipgloss"
	"github.com/vulcanshen/kbu/internal/k8s"
	"github.com/vulcanshen/kbu/internal/theme"
)

type StatusBarModel struct {
	clusterInfo k8s.ClusterInfo
	namespace   string
	width       int
	activePanel Panel
	theme       *theme.Theme
}

func NewStatusBarModel(t *theme.Theme, info k8s.ClusterInfo) StatusBarModel {
	return StatusBarModel{
		clusterInfo: info,
		namespace:   "All Namespaces",
		activePanel: SidebarPanel,
		theme:       t,
	}
}

func (m *StatusBarModel) SetClusterInfo(info k8s.ClusterInfo) {
	m.clusterInfo = info
}

func (m *StatusBarModel) SetNamespace(ns string) {
	if ns == "" {
		m.namespace = "All Namespaces"
	} else {
		m.namespace = ns
	}
}

func (m *StatusBarModel) SetWidth(width int) {
	m.width = width
}

// SetActivePanel lets the status bar adapt its bracket-hotkey markers to
// the currently focused panel. The `C` accelerator is panel-aware (panel 2
// hijacks it for Compare), so on panel 2 the `[C]ontext:` label drops its
// brackets — `C` won't open the context picker from there. Other labels
// stay bracketed because their hotkeys are global.
func (m *StatusBarModel) SetActivePanel(p Panel) {
	m.activePanel = p
}

// PtyMarker is a pointer-as-flag — nil means "don't render", non-nil
// means "Alterm shell is alive but hidden; show the [Alt-t]erm chip
// so the user knows it's in the background and Alt+T toggles it."
//
// Pre-v1.7.6 this struct carried Visible + Label fields, but the
// production caller only ever set Visible=false (hidden = the only
// state the chip is for) and Label was a glyph-prefixed string.
// v1.7.6 switched to bracket-hotkey format consistent with [C]ontext
// / [N]amespace, so the chip content is now generated by statusbar
// itself — no caller-supplied label.
type PtyMarker struct{}

// CompareMarker tags compare-mode-active. Same pointer-as-flag shape
// as PtyMarker; statusbar renders "[C]ompare" with panel-aware
// dimming on [C] anti-correlated to [C]ontext (lit on panel 2 where
// C means compare, dim on panels 1/3 where C means context). The
// chip's PRESENCE signals "anchor set"; the [C] brightness signals
// "C will / won't fire compare on the active panel".
type CompareMarker struct{}

func (m StatusBarModel) View() string {
	return m.ViewWithErrors(0)
}

func (m StatusBarModel) ViewWithErrors(unreadErrors int) string {
	return m.ViewWithBadge(unreadErrors, "")
}

func (m StatusBarModel) ViewWithBadge(unreadErrors int, successNotice string) string {
	return m.ViewFull(unreadErrors, 0, successNotice, nil, nil)
}

// ViewFull renders the status bar with optional PTY + compare markers.
// Markers sit in the LEFT segment after the namespace label so they don't
// fight the error / warn / success badge on the right for space.
//
// Badge precedence: error (red) > warn (peach) > success (green) > none.
// Splitting warn from error lets non-critical nudges (deprecation, transient
// hiccups) surface a Catppuccin Peach ` N warnings` badge without
// firing the red `! N errors` signal that should mean real failure. The
// `` glyph is the Nerd Font Font-Awesome warning triangle, picked
// over the unicode `⚠` (U+26A0) per design-guide §3.2 (glyphs limited
// to the U+F... Nerd Font private-use range).
func (m StatusBarModel) ViewFull(unreadErrors, unreadWarns int, successNotice string, pty *PtyMarker, compare *CompareMarker) string {
	// `[C]ontext: <ctx>  [N]amespace: <ns>` — multi-segment rendering
	// with semantic coloring instead of layout-shifting bracket markers:
	//   • brackets `[ ]`: blue (theme ContextFg)
	//   • hotkey letter `C` / `N` when ACTIVE: catppuccin green
	//   • filler text `ontext:` / `amespace:`: catppuccin overlay1 grey
	//   • hotkey letter when INACTIVE: same grey as filler
	//   • values <ctx>/<ns>: catppuccin lavender — same accent as the
	//     sidebar Pinned section, so the user-relevant identifiers
	//     (this kube context, this namespace, your pinned kinds)
	//     share a visual signature across the app
	// `C` is panel-aware (panel 2 hijacks it for Compare). On panel 2
	// the whole `[C]` (brackets + letter) collapses to grey — signals
	// "not a shortcut here" without any width change. `N` is global,
	// stays bright blue everywhere.
	//
	// Cluster slot dropped because context already binds (cluster, user)
	// — surfacing both was duplicating the same signal. Previous NF
	// glyphs (U+F0237 context, U+F51E namespace) migrated to the popup
	// titles so the icon-to-concept association stays.
	blueStyle := lipgloss.NewStyle().Foreground(lipgloss.Color(m.theme.StatusBar.ContextFg))
	greyStyle := lipgloss.NewStyle().Foreground(lipgloss.Color("#7f849c"))
	valueStyle := lipgloss.NewStyle().Foreground(lipgloss.Color("#b4befe"))

	cBracketStyle := blueStyle
	if m.activePanel == TablePanel {
		cBracketStyle = greyStyle
	}
	ctx := cBracketStyle.Render("[C]") +
		greyStyle.Render("ontext: ") + valueStyle.Render(m.clusterInfo.ContextName)
	ns := blueStyle.Render("[N]") +
		greyStyle.Render("amespace: ") + valueStyle.Render(m.namespace)

	barStyle := m.theme.StatusBarStyle().Padding(0, 0)
	badgeStyle := lipgloss.NewStyle().Foreground(lipgloss.Color("#1e1e2e")).Bold(true)

	left := fmt.Sprintf(" %s  %s", ctx, ns)
	if pty != nil {
		// [Alt-t]erm — bracket-hotkey format mirroring [C]ontext /
		// [N]amespace so "anything bracketed on the statusbar is a
		// hotkey" stays one rule (not two). Alt+T is global so the
		// bracket+letter is always blue (active); no panel-aware
		// dimming needed.
		altermChip := blueStyle.Render("[Alt-t]") + greyStyle.Render("erm")
		left = left + "  " + altermChip
	}
	if compare != nil {
		// [C]ompare — same bracket-hotkey format. Panel-aware [C]
		// dimming is anti-correlated to [C]ontext: on panel 2 the
		// table hijacks C for compare actions, so [C]ontext's [C]
		// dims and [C]ompare's [C] lights up. On panel 1/3 it's the
		// reverse — C means context picker, so this chip's [C] dims
		// to signal "pressing C here will NOT fire compare". The
		// chip's PRESENCE alone still means "anchor set"; brightness
		// is the panel-routed handoff signal.
		cmpBracketStyle := greyStyle
		if m.activePanel == TablePanel {
			cmpBracketStyle = blueStyle
		}
		compareChip := cmpBracketStyle.Render("[C]") + greyStyle.Render("ompare")
		left = left + "  " + compareChip
	}

	var badgePart string
	switch {
	case unreadErrors > 0:
		badgeText := fmt.Sprintf(" ! %d errors ", unreadErrors)
		badgePart = badgeStyle.Background(lipgloss.Color(m.theme.Status.Error)).Render(badgeText)
	case unreadWarns > 0:
		// Catppuccin Peach — same hue as toast warn border. The warn
		// badge is visually distinct from the error red so deprecation
		// nudges / non-critical events don't get conflated with real
		// failures.
		label := "warnings"
		if unreadWarns == 1 {
			label = "warning"
		}
		badgeText := fmt.Sprintf("  %d %s ", unreadWarns, label)
		badgePart = badgeStyle.Background(lipgloss.Color(toastWarnColor)).Render(badgeText)
	case successNotice != "":
		badgeText := fmt.Sprintf(" ✓ %s ", successNotice)
		badgePart = badgeStyle.Background(lipgloss.Color(m.theme.Status.Running)).Render(badgeText)
	}

	if badgePart == "" {
		return barStyle.Width(m.width).Render(left)
	}
	leftPart := barStyle.Width(m.width - lipgloss.Width(badgePart)).Render(left)
	return leftPart + badgePart
}

func (m StatusBarModel) Height() int {
	return lipgloss.Height(m.View())
}
